<?php
/**
 * Vietnam states
 *
 * @package WooCommerce/i18n
 * @version 2.0.0
 */

defined( 'ABSPATH' ) || exit;

$states['VN'] = array(
	'VN-44' => __( 'An Giang', 'dhl-for-woocommerce' ),
	'VN-43' => __( 'Bà Rịa–Vũng Tàu', 'dhl-for-woocommerce' ),
	'VN-54' => __( 'Bắc Giang', 'dhl-for-woocommerce' ),
	'VN-53' => __( 'Bắc Kạn', 'dhl-for-woocommerce' ),
	'VN-55' => __( 'Bạc Liêu', 'dhl-for-woocommerce' ),
	'VN-56' => __( 'Bắc Ninh', 'dhl-for-woocommerce' ),
	'VN-50' => __( 'Bến Tre', 'dhl-for-woocommerce' ),
	'VN-31' => __( 'Bình Định', 'dhl-for-woocommerce' ),
	'VN-57' => __( 'Bình Dương', 'dhl-for-woocommerce' ),
	'VN-58' => __( 'Bình Phước', 'dhl-for-woocommerce' ),
	'VN-40' => __( 'Bình Thuận', 'dhl-for-woocommerce' ),
	'VN-59' => __( 'Cà Mau', 'dhl-for-woocommerce' ),
	'VN-CT' => __( 'Cần Thơ', 'dhl-for-woocommerce' ),
	'VN-04' => __( 'Cao Bằng', 'dhl-for-woocommerce' ),
	'VN-DN' => __( 'Đà Nẵng', 'dhl-for-woocommerce' ),
	'VN-33' => __( 'Đắk Lắk', 'dhl-for-woocommerce' ),
	'VN-72' => __( 'Đắk Nông', 'dhl-for-woocommerce' ),
	'VN-71' => __( 'Điện Biên', 'dhl-for-woocommerce' ),
	'VN-39' => __( 'Đồng Nai', 'dhl-for-woocommerce' ),
	'VN-45' => __( 'Đồng Tháp', 'dhl-for-woocommerce' ),
	'VN-30' => __( 'Gia Lai', 'dhl-for-woocommerce' ),
	'VN-03' => __( 'Hà Giang', 'dhl-for-woocommerce' ),
	'VN-63' => __( 'Hà Nam', 'dhl-for-woocommerce' ),
	'VN-HN' => __( 'Hà Nội', 'dhl-for-woocommerce' ),
	'VN-23' => __( 'Hà Tĩnh', 'dhl-for-woocommerce' ),
	'VN-61' => __( 'Hải Dương', 'dhl-for-woocommerce' ),
	'VN-HP' => __( 'Hải Phòng', 'dhl-for-woocommerce' ),
	'VN-73' => __( 'Hậu Giang', 'dhl-for-woocommerce' ),
	'VN-SG' => __( 'Hồ Chí Minh', 'dhl-for-woocommerce' ),
	'VN-14' => __( 'Hòa Bình', 'dhl-for-woocommerce' ),
	'VN-66' => __( 'Hưng Yên', 'dhl-for-woocommerce' ),
	'VN-34' => __( 'Khánh Hòa', 'dhl-for-woocommerce' ),
	'VN-47' => __( 'Kiên Giang', 'dhl-for-woocommerce' ),
	'VN-28' => __( 'Kon Tum', 'dhl-for-woocommerce' ),
	'VN-01' => __( 'Lai Châu', 'dhl-for-woocommerce' ),
	'VN-35' => __( 'Lâm Đồng', 'dhl-for-woocommerce' ),
	'VN-09' => __( 'Lạng Sơn', 'dhl-for-woocommerce' ),
	'VN-02' => __( 'Lào Cai', 'dhl-for-woocommerce' ),
	'VN-41' => __( 'Long An', 'dhl-for-woocommerce' ),
	'VN-67' => __( 'Nam Định', 'dhl-for-woocommerce' ),
	'VN-22' => __( 'Nghệ An', 'dhl-for-woocommerce' ),
	'VN-18' => __( 'Ninh Bình', 'dhl-for-woocommerce' ),
	'VN-36' => __( 'Ninh Thuận', 'dhl-for-woocommerce' ),
	'VN-68' => __( 'Phú Thọ', 'dhl-for-woocommerce' ),
	'VN-32' => __( 'Phú Yên', 'dhl-for-woocommerce' ),
	'VN-24' => __( 'Quảng Bình', 'dhl-for-woocommerce' ),
	'VN-27' => __( 'Quảng Nam', 'dhl-for-woocommerce' ),
	'VN-29' => __( 'Quảng Ngãi', 'dhl-for-woocommerce' ),
	'VN-13' => __( 'Quảng Ninh', 'dhl-for-woocommerce' ),
	'VN-25' => __( 'Quảng Trị', 'dhl-for-woocommerce' ),
	'VN-52' => __( 'Sóc Trăng', 'dhl-for-woocommerce' ),
	'VN-05' => __( 'Sơn La', 'dhl-for-woocommerce' ),
	'VN-37' => __( 'Tây Ninh', 'dhl-for-woocommerce' ),
	'VN-20' => __( 'Thái Bình', 'dhl-for-woocommerce' ),
	'VN-69' => __( 'Thái Nguyên', 'dhl-for-woocommerce' ),
	'VN-21' => __( 'Thanh Hóa', 'dhl-for-woocommerce' ),
	'VN-26' => __( 'Thừa Thiên–Huế', 'dhl-for-woocommerce' ),
	'VN-46' => __( 'Tiền Giang', 'dhl-for-woocommerce' ),
	'VN-51' => __( 'Trà Vinh', 'dhl-for-woocommerce' ),
	'VN-07' => __( 'Tuyên Quang', 'dhl-for-woocommerce' ),
	'VN-49' => __( 'Vĩnh Long', 'dhl-for-woocommerce' ),
	'VN-70' => __( 'Vĩnh Phúc', 'dhl-for-woocommerce' ),
	'VN-06' => __( 'Yên Bái', 'dhl-for-woocommerce' )
);
