<?php
/**
 * Vietnam states
 *
 * @package WooCommerce/i18n
 * @version 2.0.0
 */

defined( 'ABSPATH' ) || exit;

$states['VN'] = array(
	'VN-44' => esc_html__( 'An Giang', 'dhl-for-woocommerce' ),
	'VN-43' => esc_html__( 'Bà Rịa–Vũng Tàu', 'dhl-for-woocommerce' ),
	'VN-54' => esc_html__( 'Bắc Giang', 'dhl-for-woocommerce' ),
	'VN-53' => esc_html__( 'Bắc Kạn', 'dhl-for-woocommerce' ),
	'VN-55' => esc_html__( 'Bạc Liêu', 'dhl-for-woocommerce' ),
	'VN-56' => esc_html__( 'Bắc Ninh', 'dhl-for-woocommerce' ),
	'VN-50' => esc_html__( 'Bến Tre', 'dhl-for-woocommerce' ),
	'VN-31' => esc_html__( 'Bình Định', 'dhl-for-woocommerce' ),
	'VN-57' => esc_html__( 'Bình Dương', 'dhl-for-woocommerce' ),
	'VN-58' => esc_html__( 'Bình Phước', 'dhl-for-woocommerce' ),
	'VN-40' => esc_html__( 'Bình Thuận', 'dhl-for-woocommerce' ),
	'VN-59' => esc_html__( 'Cà Mau', 'dhl-for-woocommerce' ),
	'VN-CT' => esc_html__( 'Cần Thơ', 'dhl-for-woocommerce' ),
	'VN-04' => esc_html__( 'Cao Bằng', 'dhl-for-woocommerce' ),
	'VN-DN' => esc_html__( 'Đà Nẵng', 'dhl-for-woocommerce' ),
	'VN-33' => esc_html__( 'Đắk Lắk', 'dhl-for-woocommerce' ),
	'VN-72' => esc_html__( 'Đắk Nông', 'dhl-for-woocommerce' ),
	'VN-71' => esc_html__( 'Điện Biên', 'dhl-for-woocommerce' ),
	'VN-39' => esc_html__( 'Đồng Nai', 'dhl-for-woocommerce' ),
	'VN-45' => esc_html__( 'Đồng Tháp', 'dhl-for-woocommerce' ),
	'VN-30' => esc_html__( 'Gia Lai', 'dhl-for-woocommerce' ),
	'VN-03' => esc_html__( 'Hà Giang', 'dhl-for-woocommerce' ),
	'VN-63' => esc_html__( 'Hà Nam', 'dhl-for-woocommerce' ),
	'VN-HN' => esc_html__( 'Hà Nội', 'dhl-for-woocommerce' ),
	'VN-23' => esc_html__( 'Hà Tĩnh', 'dhl-for-woocommerce' ),
	'VN-61' => esc_html__( 'Hải Dương', 'dhl-for-woocommerce' ),
	'VN-HP' => esc_html__( 'Hải Phòng', 'dhl-for-woocommerce' ),
	'VN-73' => esc_html__( 'Hậu Giang', 'dhl-for-woocommerce' ),
	'VN-SG' => esc_html__( 'Hồ Chí Minh', 'dhl-for-woocommerce' ),
	'VN-14' => esc_html__( 'Hòa Bình', 'dhl-for-woocommerce' ),
	'VN-66' => esc_html__( 'Hưng Yên', 'dhl-for-woocommerce' ),
	'VN-34' => esc_html__( 'Khánh Hòa', 'dhl-for-woocommerce' ),
	'VN-47' => esc_html__( 'Kiên Giang', 'dhl-for-woocommerce' ),
	'VN-28' => esc_html__( 'Kon Tum', 'dhl-for-woocommerce' ),
	'VN-01' => esc_html__( 'Lai Châu', 'dhl-for-woocommerce' ),
	'VN-35' => esc_html__( 'Lâm Đồng', 'dhl-for-woocommerce' ),
	'VN-09' => esc_html__( 'Lạng Sơn', 'dhl-for-woocommerce' ),
	'VN-02' => esc_html__( 'Lào Cai', 'dhl-for-woocommerce' ),
	'VN-41' => esc_html__( 'Long An', 'dhl-for-woocommerce' ),
	'VN-67' => esc_html__( 'Nam Định', 'dhl-for-woocommerce' ),
	'VN-22' => esc_html__( 'Nghệ An', 'dhl-for-woocommerce' ),
	'VN-18' => esc_html__( 'Ninh Bình', 'dhl-for-woocommerce' ),
	'VN-36' => esc_html__( 'Ninh Thuận', 'dhl-for-woocommerce' ),
	'VN-68' => esc_html__( 'Phú Thọ', 'dhl-for-woocommerce' ),
	'VN-32' => esc_html__( 'Phú Yên', 'dhl-for-woocommerce' ),
	'VN-24' => esc_html__( 'Quảng Bình', 'dhl-for-woocommerce' ),
	'VN-27' => esc_html__( 'Quảng Nam', 'dhl-for-woocommerce' ),
	'VN-29' => esc_html__( 'Quảng Ngãi', 'dhl-for-woocommerce' ),
	'VN-13' => esc_html__( 'Quảng Ninh', 'dhl-for-woocommerce' ),
	'VN-25' => esc_html__( 'Quảng Trị', 'dhl-for-woocommerce' ),
	'VN-52' => esc_html__( 'Sóc Trăng', 'dhl-for-woocommerce' ),
	'VN-05' => esc_html__( 'Sơn La', 'dhl-for-woocommerce' ),
	'VN-37' => esc_html__( 'Tây Ninh', 'dhl-for-woocommerce' ),
	'VN-20' => esc_html__( 'Thái Bình', 'dhl-for-woocommerce' ),
	'VN-69' => esc_html__( 'Thái Nguyên', 'dhl-for-woocommerce' ),
	'VN-21' => esc_html__( 'Thanh Hóa', 'dhl-for-woocommerce' ),
	'VN-26' => esc_html__( 'Thừa Thiên–Huế', 'dhl-for-woocommerce' ),
	'VN-46' => esc_html__( 'Tiền Giang', 'dhl-for-woocommerce' ),
	'VN-51' => esc_html__( 'Trà Vinh', 'dhl-for-woocommerce' ),
	'VN-07' => esc_html__( 'Tuyên Quang', 'dhl-for-woocommerce' ),
	'VN-49' => esc_html__( 'Vĩnh Long', 'dhl-for-woocommerce' ),
	'VN-70' => esc_html__( 'Vĩnh Phúc', 'dhl-for-woocommerce' ),
	'VN-06' => esc_html__( 'Yên Bái', 'dhl-for-woocommerce' ),
);
